name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # only trigger on tags starting with 'v' (e.g., v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build distribution
        run: |
          python -m pip install --upgrade build
          python -m build  # creates dist/*.tar.gz and dist/*.whl

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
